name: Atualização no Feed da ${{ github.actor }}
run-name: Alguém publicou no site da ${{ github.actor }}

on: 
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:

  update-blog:
    name: ${{ github.actor }} is update her Feed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path : ./docs/README.md
          comment_tag_name: "BLOG"
          feed_list: "https://feeds.feedburner.com/camilaloliveira/feed"
          max_post_count: "4"
          remove_duplicates: true
  
  update-youtube: 
    name: ${{ github.actor }} is update her YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path : ./docs/README.md
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCRJXkK-HE9N6sgaGd1JYuKw"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "dd, mm, yyyy"
          template: '<table><tr><td width="250px"><a href="$url"><img width="200px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td width="800px"><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
          max_post_count: "4"
          remove_duplicates: true
        
