configuraÃ§Ãµes:
  nome de usuÃ¡rio: clcmo
  commit_msg: â€œâš¡ Atualizar README com a atividade recenteâ€
  max_lines: 5
  readme_file: â€œ./docs/README.mdâ€
  disabled_events:
    - â€œcomentÃ¡riosâ€
  url_text: â€œ{REPO}{ID}â€
  date:
    timezone: â€œGMT-03:00â€
    text: â€œÃšltima atualizacao: {DATE}â€
    format: â€œdddd, mmmm dS, yyyy, h:MM:ss TTâ€
  commit_name: â€œreadme-botâ€
  commit_email: â€œ41898282+github-actions[bot]@users.noreply.github.comâ€
  prefixo_de_linha: â€œ{NUM}. â€
  repositÃ³rios_ignorados:
    - clcmo/clcmo
mensagens:
  comentÃ¡rios: â€œğŸ’¬ Comentou em {ID} em {REPO}â€
  push: â€œâ¬†ï¸ Enviou {AMOUNT} commit(s) para {REPO}â€
  issue_opened: â€œâ—ï¸ Abriu a questao {ID} em {REPO}â€
  issue_closed: â€œâœ”ï¸ Fechou a questao {ID} em {REPO}â€
  pr_opened: â€œğŸ’ª PR {ID} aberto em {REPO}â€
  pr_closed: â€œâŒ PR {ID} fechado em {REPO}â€
  pr_merged: â€œğŸ‰ PR {ID} mesclado em {REPO}â€
  create_repo: â€œğŸ“” Novo repositorio {REPO} criadoâ€
  fork_repo: â€œğŸ”± {FORK} bifurcado de {REPO}â€
  wiki_create: â€œğŸ“– Nova pagina wiki {WIKI} criada em {REPO}â€
  added_member: â€œğŸ¤ Tornei-me colaborador em {REPO}â€
  changes_approved: â€œğŸ‘ {ID} aprovado em {REPO}â€
  changes_requested: â€œğŸ”´ Alteracoes solicitadas em {ID} em {REPO}â€
  new_release: â€œâœŒï¸ {ID} lancado em {REPO}â€
  new_star: â€œâ­ {REPO} marcado com estrelaâ€
